# Generated by Django 2.2.7 on 2020-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200324_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='9548637', max_length=10, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default=' 1', max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
