# Generated by Django 3.0.5 on 2020-04-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200324_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='4206994', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
