# Generated by Django 3.0.5 on 2020-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200429_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='3084161', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
