# Generated by Django 3.0.5 on 2020-04-30 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200430_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/profile/unknown.jpg', null=True, upload_to='users/', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 7, 8, 32, 23157, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='6743078', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
