# Generated by Django 3.0.5 on 2020-04-30 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200430_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='1048923', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
