# Generated by Django 3.0.5 on 2020-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200430_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='4507474', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
