# Generated by Django 3.0.5 on 2020-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200430_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='563957', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
