# Generated by Django 3.0.5 on 2020-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200514_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default='7672320', max_length=10, unique=True, verbose_name='url'),
        ),
    ]
