# Generated by Django 2.2.7 on 2020-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, verbose_name='вкл/выкл')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='url')),
                ('edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикация')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('template', models.CharField(default='pages/home.html', max_length=500, verbose_name='Шаблон')),
                ('registration_required', models.BooleanField(default=False, help_text='Если флажок установлен, только зарегестрированные пользователи могут просматривать страницу', verbose_name='Требуется регистрация')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
