# Generated by Django 2.2.7 on 2020-01-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200103_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='url',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='url на внешний ресурс'),
        ),
    ]
